#
# Module manifest for module 'PowerShellAccessControl'
#
# Generated by: Rohn Edwards
#
# Generated on: 7/3/2013
#

@{

# Version number of this module.
ModuleVersion = '3.0.135.20150413'

# ID used to uniquely identify this module
GUID = '3b5f7697-05d6-4f5e-9b71-6841be80f7d8'

# Author of this module
Author = 'Rohn Edwards'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2013 Rohn Edwards. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides an easy way to view and modify security descriptors for most securable objects in Windows, including files, folders, registry keys, services, printers, shares, processes, and more. Most actions possible from the ACL Editor GUI can be performed with this module.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = 'PowerShellAccessControlPInvokeSignatures.ps1', 'PowerShellAccessControlAccessMaskEnumerations.ps1'

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = 'PowerShellAccessControl.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'PowerShellAccessControl.format.ps1xml'

ModuleToProcess = 'PowerShellAccessControl.psm1'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'ConvertTo-Win32SecurityDescriptor', 
                    'ConvertFrom-Win32SecurityDescriptor', 
                    'Get-Win32SecurityDescriptor', 
                    'Get-AccessControlEntry', 
                    'New-AccessControlEntry', 
                    'New-AdaptedSecurityDescriptor', 
                    'Get-SecurityDescriptor', 
                    'Set-SecurityDescriptor', 
                    'Disable-AclInheritance', 
                    'Enable-AclInheritance', 
                    'Add-AccessControlEntry', 
                    'Remove-AccessControlEntry',
                    'Set-Owner',
                    'Get-EffectiveAccess',
                    'Get-MandatoryIntegrityLabel',
                    'Repair-AclCanonicalOrder',
                    'Get-ADObjectAceGuid'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

